### PR TITLE
Added damage popup

### PR DESCRIPTION
**Pull request by Wouterz90**
image

Plain and simple damage popup over the damager.

### CODE REVIEW

**Comment by Wouterz90** [comment]
This also confirmed there is an issue with flesh heaps in long range kills (I believe it's something like over 1500 units). So it does work when killing units outside of the cast range but there is something hidden in the function that detects heroes being killed nearby. I'll try experimenting with a modifier doing all the work but I wonder if it works from level 0 to track kills like this does.

**Comment by darklordabc** [comment]
looks good

**Comment by darklordabc** [comment]
My only concern that it will be too frequent, but I'll test it soon.

**Comment by Yahnich** [comment]
why did you add the function, it's already in utility

**Comment by darklordabc** [comment]
I got this error when I threw hellfire blast at a neutral creep
[   Developer              ]: ...cripts\vscripts\abilities\pudge_flesh_heap_spell_amp.lua:136: attempt to index global 'victim' (a nil value)
```
[   Developer              ]: 	...cripts\vscripts\abilities\pudge_flesh_heap_spell_amp.lua:136: in function <...cripts\vscripts\abilities\pudge_flesh_heap_spell_amp.lua:126>
[ W VScript                ]: Script Runtime Error: ...cripts\vscripts\abilities\pudge_flesh_heap_spell_amp.lua:136: attempt to index global 'victim' (a nil value)
[ W VScript                ]: stack traceback:
[ W VScript                ]: 	...cripts\vscripts\abilities\pudge_flesh_heap_spell_amp.lua:136: in function <...cripts\vscripts\abilities\pudge_flesh_heap_spell_amp.lua:126>
```

Could you maybe merge this into your other fleash heap related PR?

**Comment by Wouterz90** [comment]
I copied the function from some example that was showed to me, and it has a different name. Will change, tyvm.

Will look into the issue

**Pull request closed without merging**
